# Generated by Django 6.0.1 on 2026-01-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_deal_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.account'),
        ),
    ]
