# Generated by Django 6.0.1 on 2026-01-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_tagged_users_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='service_requirement',
            field=models.CharField(blank=True, choices=[('Website Development', 'Website Development'), ('Website Maintenance', 'Website Maintenance'), ('Mobile App Development', 'Mobile App Development'), ('E-Commerce Solutions', 'E-Commerce Solutions'), ('SEO & Digital Marketing', 'SEO & Digital Marketing'), ('UI/UX Design', 'UI/UX Design'), ('Cloud Solutions', 'Cloud Solutions'), ('Consulting', 'Consulting'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
