# Generated by Django 6.0.1 on 2026-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_service_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_person_phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='service_requirement',
            field=models.CharField(choices=[('Website Development', 'Website Development'), ('Website Maintenance', 'Website Maintenance'), ('Mobile App Development', 'Mobile App Development'), ('E-Commerce Solutions', 'E-Commerce Solutions'), ('SEO & Digital Marketing', 'SEO & Digital Marketing'), ('UI/UX Design', 'UI/UX Design'), ('Cloud Solutions', 'Cloud Solutions'), ('Consulting', 'Consulting'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
