# Generated by Django 6.0.1 on 2026-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_account_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_person_name',
            field=models.CharField(default='Unknown Contact', max_length=255),
        ),
    ]
