# Generated by Django 6.0.1 on 2026-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_person_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('email', 'Email'), ('mom', 'MoM')], default='note', max_length=10),
        ),
    ]
