# Generated by Django 6.0.1 on 2026-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_contact_person_title_contactnote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
