# Generated by Django 6.0.1 on 2026-01-26 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_financetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted')], max_length=10)),
                ('comment', models.TextField()),
                ('data_snapshot', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Audit',
                'verbose_name_plural': 'Transaction Audits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
