# Generated by Django 6.0.1 on 2026-01-26 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transactionaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance AI Report',
                'verbose_name_plural': 'Finance AI Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
